_BASE_: "./da_pro_faster_rcnn_R_50_C4.yaml"
MODEL:
  CLIP:
    MULTIPLY_RPN_SCORE: True
  ROI_HEADS:
    SOFT_NMS_ENABLED: False
INPUT:
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 2048
  MAX_SIZE_TEST: 2048
LEARNABLE_PROMPT:
  CTX_SIZE: 10
  TUNING: False
